### ISSUE TITLE
Finish the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-anniavdc#1]
Good work @anniavdc  !!!

Here you have some tips to finish the game:

- [x] On page load, execute 'getRandomNumber' function and store the returned value on a constant to work with it later.
- [x] Use ONE `addEventListener` for each event. If you need to execute multiple functions at once perhaps you can call them inside your unique handler
- [x] Don't use a `return` statement in a callback to return a value because it's not possible to get the value in the `addEventListener`
- [x] Define the logic to make the counter work
- [x] Indent and avoid extra white spaces to improve readability and prevent bugs
- [x] Remove commented code

Let me know if you have any doubts ;)

Go for it!!

**Comment by anniavdc** [comment]
@nasivuela I was working on it yesterday and I think it's all done on improvements branch, do I have to do the changes on master branch also? I also erased the steps comments.

I used several listener to check it the functions where working ok with the click but I have a doubt: I saw that I was comparing two functions but without executing them, and after I execute them, I saw that I was generating several random numbers... so I did what you are saying, stored  the return value on a constant, but about not using a return statetement in a callback, that means that I store the value in a constant inside the handler's function right? At least that's how it's working now in the improvements branch, let me know if it is ok.

**Comment by nasivuela** [comment]
@anniavdc from now on feel free to merge into master.

And the answer to your question is YES! You have done it beautifully! Actually, if you remove the log into 'getUserNumber' it will be a function with only one expression which result is returned. What about converting it to an arrow function? And then you can make it a one-line arrow function, without brackets and return keyword :D

Also here you have more improvements to keep practicing:

- [x] Make your code cleaner removing logs
- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "userResult.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'userResult'?

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

**Comment by anniavdc** [comment]
@nasivuela I've merged to master branch and I think the second improvements are done, I also tried to use more arrow functions, I hope they're ok.

**Comment by nasivuela** [comment]
Sweet!!!

![](https://media.giphy.com/media/3boPPdHk2ueo8/giphy.gif)

PD. Watch out it's not in master yet!
